import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer/Footer";
import Headers from "@/components/Headers/Headers";
import ClientWrapper from "@/components/ClientWrapper/ClientWrapper";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sellkar Theme",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <ClientWrapper>
          <header>
            <Headers />
          </header>


          {children}



          <footer>
            <Footer />
          </footer>
        </ClientWrapper>


      </body>
    </html>
  );
}
